name: Check Build on PR

defaults:
  run:
    working-directory: client

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_NEXT_PUBLIC_API_KEY: ${{ vars.NEXT_PUBLIC_API_KEY }}
          envkey_NEXT_PUBLIC_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_AUTH_DOMAIN }}
          envkey_NEXT_PUBLIC_PROJECT_ID: ${{ vars.NEXT_PUBLIC_PROJECT_ID }}
          envkey_NEXT_PUBLIC_STORAGE_BUCKET: ${{ vars.NEXT_PUBLIC_STORAGE_BUCKET }}
          envkey_NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ vars.NEXT_PUBLIC_MESSAGING_SENDER_ID }}
          envkey_NEXT_PUBLIC_APP_ID: ${{ vars.NEXT_PUBLIC_APP_ID }}
          envkey_NEXT_PUBLIC_TIKZ_TO_SVG_SERVER_URL: ${{ vars.NEXT_PUBLIC_TIKZ_TO_SVG_SERVER_URL }}
          directory: client
          file_name: .env
          fail_on_empty: false
      - run: yarn install && yarn build
